import org.example.models.driver.Driver;
import org.example.models.enums.RideStatus;
import org.example.models.ride.Ride;
import org.example.repository.DriverRepoImpl;
import org.example.repository.RideRepoImpl;
import org.example.response.RideResponse;
import org.example.service.FindCabServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

public class findCabServiceTest {

    private FindCabServiceImpl rideService;
    private DriverRepoImpl driverRepo;
    private RideRepoImpl rideRepo;

    @BeforeEach
    void setUp() {
        driverRepo = new DriverRepoImpl(); // your in-memory repo
        rideRepo = new RideRepoImpl();     // your in-memory repo
        rideService = new FindCabServiceImpl(driverRepo, rideRepo);
    }

    @Test
    void testRegisterDriverAutoGenerated() {
        double x = 10.0, y = 20.0;
        boolean available = true;

        int driverId = rideService.registerDriver(null, x, y, available);
        assertTrue(driverId >= 0, "Driver ID should be generated");

        Optional<Driver> driverOpt = driverRepo.findDriverById(driverId);
        assertTrue(driverOpt.isPresent());
        Driver driver = driverOpt.get();
        assertEquals(x, driver.getXCoordinates());
        assertEquals(y, driver.getYCoordinates());
        assertTrue(driver.isAvailable());
    }

    @Test
    void testRequestRideAllocatesNearestDriver() {
        // register two drivers
        int driver1 = rideService.registerDriver(null, 0, 0, true);
        int driver2 = rideService.registerDriver(null, 10, 10, true);

        // request ride near (1,1)
        Optional<RideResponse> rideOpt = rideService.requestRide(101, 1, 1);
        assertTrue(rideOpt.isPresent());
        RideResponse ride = rideOpt.get();

        // nearest driver should be driver1
        assertEquals(driver1, ride.driverId);

        // driver1 should now be unavailable
        Driver d1 = driverRepo.findDriverById(driver1).get();
        assertFalse(d1.isAvailable());
    }

    @Test
    void testCompleteRideMakesDriverAvailableAgain() {
        int driverId = rideService.registerDriver(null, 5, 5, true);
        Optional<RideResponse> rideOpt = rideService.requestRide(201, 5, 5);
        assertTrue(rideOpt.isPresent());

        int rideId = rideOpt.get().rideId;

        // Complete the ride
        boolean completed = rideService.completeRide(rideId);
        assertTrue(completed);

        Driver driver = driverRepo.findDriverById(driverId).get();
        assertTrue(driver.isAvailable());

        // Ride status should be COMPLETED
        Ride ride = rideService.findRideById(rideId).get();
        assertEquals(RideStatus.COMPLETED, ride.getStatus());
    }

    @Test
    void testRequestRideReturnsEmptyWhenNoDrivers() {
        Optional<RideResponse> rideOpt = rideService.requestRide(999, 0, 0);
        assertTrue(rideOpt.isEmpty());
    }

    void testGetNearestAvailableDriversLimit() {
        rideService.registerDriver(null, 0, 0, true);
        rideService.registerDriver(null, 10, 0, true);
        rideService.registerDriver(null, 5, 5, true);

        List<Driver> nearest = rideService.getNearestAvailableDrivers(0, 0, 2);
        assertEquals(2, nearest.size());

        // nearest driver should be at (0,0)
        assertEquals(0, nearest.get(0).getXCoordinates());
        assertEquals(0, nearest.get(0).getYCoordinates());
    }

}
